services:
  user-service:
    build: ./services/user-service
    container_name: user-service
    restart: always
    environment:
      DATABASE_URL: ${DATABASE_URL_USER}
      DATABASE_URL_REPLICA: ${DATABASE_URL_USER_REPLICA} 
      JWT_SECRET: ${JWT_SECRET}
      PORT: 3000
      REDIS_URL: ${REDIS_URL}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}
      SMTP_FROM: ${SMTP_FROM}
    ports:
      - "3000:3000"

  driver-service:
    build: ./services/driver-service
    container_name: driver-service
    restart: always
    environment:
      PORT: 3001
      REDIS_URL: ${REDIS_URL}
      ONLINE_TTL_SECONDS: ${ONLINE_TTL_SECONDS}
    ports:
      - "3001:3001"

  trip-service:
    build: ./services/trip-service
    container_name: trip-service
    restart: always
    depends_on:
      driver-service:
        condition: service_started
    environment:
      DATABASE_URL: ${DATABASE_URL_TRIP}
      DATABASE_URL_REPLICA: ${DATABASE_URL_TRIP_REPLICA} 
      DRIVER_SERVICE_URL: http://driver-service:3001
      REDIS_URL: ${REDIS_URL}
      JWT_SECRET: ${JWT_SECRET}
      PORT: 3002
      # [MỚI] Thêm cấu hình AWS SQS
      AWS_REGION: ${AWS_REGION}
      SQS_QUEUE_URL: ${SQS_QUEUE_URL}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    ports:
      - "3002:3002"

  # [MỚI] Thêm Worker Service
  worker-service:
    build: ./services/worker-service
    container_name: worker-service
    restart: always
    depends_on:
      trip-service:
        condition: service_started
    environment:
      # Dùng chung DB với Trip để chạy Prisma
      DATABASE_URL: ${DATABASE_URL_TRIP}
      DRIVER_SERVICE_URL: http://driver-service:3001
      TRIP_SERVICE_URL: http://trip-service:3002
      AWS_REGION: ${AWS_REGION}
      SQS_QUEUE_URL: ${SQS_QUEUE_URL}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
